name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: html/
