name: Run Python Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🚀 Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit tests
        run: |
          python -m unittest discover -s laboratories/cicd-documentation -p 'test_*.py'
